#!/usr/bin/env python3
"""Regenerate `_index.md` for hypotheses, findings, decisions and protocols.

Generated files. Never hand-edit them; `--check` fails when one is stale, which
is what a forgotten regeneration looks like in CI.

The hypothesis index leads with a count per status, and that line is the point.
In the project this design was drawn from, 42% of hypothesis files never left
`idea` and nobody noticed for a year - not because the schema allowed it, but
because nothing ever showed the ratio.
"""
from __future__ import annotations

import argparse
import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent))
from _common import (  # noqa: E402
    DECISION_STATUSES, FINDING_STATUSES, HYPOTHESIS_STATUSES,
    PROTOCOL_STATUSES, find_root, iter_docs, kind_dir,
)

ORDER = {
    "hypothesis": HYPOTHESIS_STATUSES,
    "finding": FINDING_STATUSES,
    "decision": DECISION_STATUSES,
    "protocol": PROTOCOL_STATUSES,
}
HEADING = {
    "hypothesis": "Hypotheses",
    "finding": "Findings",
    "decision": "Decisions",
    "protocol": "Protocols",
}


def render(root: Path, kind: str, board: str | None) -> str:
    docs = list(iter_docs(root, kind, board))
    buckets: dict[str, list] = {s: [] for s in ORDER[kind]}
    other: list = []
    for path, meta, _ in docs:
        status = str(meta.get("status") or "")
        target = buckets[status] if status in buckets else other
        target.append((path, meta))

    counts = ", ".join(f"{s}: {len(buckets[s])}" for s in ORDER[kind])
    lines = [
        f"# {HEADING[kind]}",
        "",
        "<!-- generated by scripts/index.py - do not edit -->",
        "",
        f"**{len(docs)} total** — {counts}" + (f", other: {len(other)}" if other else ""),
        "",
    ]
    for status in ORDER[kind]:
        items = buckets[status]
        if not items:
            continue
        lines.append(f"## {status}")
        lines.append("")
        for path, meta in sorted(items, key=lambda x: str(x[1].get("id"))):
            lines.append(f"- [`{meta.get('id')}`]({path.name}) — {meta.get('title')}")
        lines.append("")
    if other:
        lines.append("## unknown status")
        lines.append("")
        for path, meta in other:
            lines.append(f"- [`{meta.get('id')}`]({path.name}) — "
                         f"{meta.get('title')} (status: {meta.get('status')!r})")
        lines.append("")
    return "\n".join(lines).rstrip("\n") + "\n"


def main() -> int:
    ap = argparse.ArgumentParser(description=__doc__,
                                 formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument("--check", action="store_true", help="fail if any index is stale")
    ap.add_argument("--root", type=Path)
    ap.add_argument("--board")
    args = ap.parse_args()

    root = args.root.resolve() if args.root else find_root()
    stale = []
    for kind in ("hypothesis", "finding", "decision", "protocol"):
        folder = kind_dir(root, kind, args.board)
        if not folder.is_dir():
            continue
        target = folder / "_index.md"
        content = render(root, kind, args.board)
        if args.check:
            current = target.read_text() if target.is_file() else ""
            if current != content:
                stale.append(target)
            continue
        target.write_text(content)
        print(target.relative_to(root) if target.is_relative_to(root) else target)

    if args.check:
        for t in stale:
            print(f"stale: {t}")
        if stale:
            print(f"\n{len(stale)} stale index file(s); run index.py")
            return 1
        print("ok - indexes current")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
